version: '3.7'

services:

  # Neo4j Graph Database
  neo4j:
    image: neo4j:enterprise
    environment:
      NEO4J_AUTH: neo4j/neo4jneo4j  # Username: neo4j, Password: test
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4JLABS_PLUGINS: '["apoc", "graph-data-science"]'
      NEO4J_dbms_security_procedures_unrestricted: 'gds.*,apoc.*'
      NEO4J_dbms_security_procedures_whitelist: 'gds.*,apoc.*'
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data

volumes:
  neo4j_data:

